service: my-api
org: mattiasahlsen
app: my-first-app

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.query
    events:
      - http:
          path: /
          method: POST
